volumes:
  kiro:
  openclaw:

networks:
  default:
    driver: bridge
  proxy:
    external: true
  
services:
  openclaw:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on: [kiro]
    image: openclaw
    container_name: openclaw
    restart: unless-stopped
    ports:
      - "127.0.0.1:18792:18792" # browser relay
      - "127.0.0.1:18793:18793" # gateway
    volumes:
      - openclaw:/home/node
    environment:
      DBUS_SESSION_BUS_ADDRESS: "unix:path=/tmp/dbus-session.sock"
      OPENCLAW_CONFIG_DIR: "/home/node/.openclaw"
      OPENCLAW_GIT_DIR: "/home/node/openclaw"
      OPENCLAW_WORKSPACE_DIR: "/home/node/.openclaw/workspace"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai.entrypoints=websecure"
      - "traefik.http.routers.ai.rule=Host(`ai.home.arpa`) && PathPrefix(`/`)"
      - "traefik.http.routers.ai.service=ai"
      - "traefik.http.routers.ai.tls=true"
      - "traefik.http.routers.ai.tls.certresolver=home_dot_arpa"
      - "traefik.http.services.ai.loadbalancer.server.port=18789"
    networks: [proxy, default]
  canvas:
    build:
      dockerfile: canvas.Dockerfile
      context: .
    image: canvas
    container_name: canvas
    depends_on: [openclaw]
    restart: unless-stopped
    volumes:
      - openclaw:/home/node
    networks: [proxy, default]
    environment:
      OPENCLAW_CANVAS_BASE_PATH: "/canvas"
      OPENCLAW_GATEWAY_WS_URL: "ws://openclaw:18789"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.canvas.entrypoints=websecure"
      - "traefik.http.routers.canvas.rule=Host(`ai.home.arpa`) && PathPrefix(`/canvas/`)"
      - "traefik.http.middlewares.canvas-stripprefix.stripprefix.prefixes=/canvas"
      - "traefik.http.routers.canvas.middlewares=canvas-stripprefix@docker"
      - "traefik.http.routers.canvas.service=canvas"
      - "traefik.http.routers.canvas.tls=true"
      - "traefik.http.routers.canvas.tls.certresolver=home_dot_arpa"
      - "traefik.http.services.canvas.loadbalancer.server.port=3456"
  kiro:
    build:
      dockerfile: kiro.Dockerfile
      context: .
    image: kiro-gateway
    container_name: kiro
    restart: unless-stopped
    volumes:
      - kiro:/home/kiro
    networks: [default]

